name: Honeycomb
version: 1.1
author: TechToolbox (@nkomarn)
main: xyz.nkomarn.Honeycomb.Honeycomb
description: A dead simple and easy to use GUI library.
website: https://nkomarn.xyz
api-version: 1.13